name: Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    name: Release Windows
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: build
      working-directory: dev/lobster
      run: msbuild.exe lobster.sln /p:Configuration=Release /p:Platform=x64
    - name: test
      run: bin/lobster.exe tests/unittest.lobster
    - name: Zip
      run: powershell Compress-Archive -Path bin, data, docs, modules, samples, tests, README.md -DestinationPath lobster_windows_release.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{ github.event.release.tag_name }}
        files: |
          lobster_windows_release.zip

  build:
    name: Release Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx: [clang++-14]
        include:
        - cxx: clang++-14
          cc: clang-14
    steps:
    - uses: actions/checkout@v1
    - name: apt update
      run: sudo apt-get -o Acquire::Retries=3 update
    - name: install opengl
      run: sudo apt-get -o Acquire::Retries=3 install mesa-common-dev libgl1-mesa-dev libgl1-mesa-glx
    - name: cmake
      working-directory: dev
      run: CXX=${{ matrix.cxx }} CC=${{ matrix.cc }} cmake -DCMAKE_BUILD_TYPE=Release -DLOBSTER_WERROR=ON .
    - name: build
      working-directory: dev
      run: make -j4
    - name: test
      run: bin/lobster tests/unittest.lobster
    - name: Zip
      run: zip lobster_linux_release.zip bin data docs modules samples tests README.md
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{ github.event.release.tag_name }}
        files: |
          lobster_linux_release.zip
